name: Label New PRs

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to new PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const isDraft = pr.draft;
            const label = isDraft ? 'draft' : 'new-pr';

            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              labels: [label]
            });
